### ISSUE TITLE
Failed to auto-detect format of key

### ISSUE THREAD

**Issue by mohammedtabish** [joyent/node-http-signature#111]
when calling the parse method it is throwing
"KeyParseError: Failed to parse (unnamed) as a valid auto format key: Failed to auto-detect format of key"
Format of the header i am getting is
{ scheme: 'Signature',
  params:
   { keyId: 'hmac-key',
     algorithm: 'hmac-sha256',
     signature: 'xxxxxxxxxxxxx',
     headers:
      [ 'accept', 'accept-encoding', 'content-type', 'date', 'digest' ] },
  signingString:
   'accept: application/vnd.drone.config.v1+json\naccept-encoding: identity\ncontent-type: application/json\ndate: Wed, 22 Apr 2020 14:53:07 GMT\ndigest: SHA-256=yyyyyyyyyyyyy',
  algorithm: 'HMAC-SHA256',
  keyId: 'hmac-key',
  opaque: undefined }

**Comment by jasonbking** [comment]
Do you have a stack trace or can provide more context? That error is coming from sshpk, and suggests that the actual key (not the keyId) used to sign or verify is missing or not a format it understands.

**Comment by mohammedtabish** [comment]
My bad , i was calling the verifySignature function instead of verifyHMAC which in my case should be used. Thanks for the reply and sorry for creating an issue.
Marking this as closed
