### ISSUE TITLE
Non constant-time hmac comparison in verify.js

### ISSUE THREAD

**Issue by alokmenghrajani** [joyent/node-http-signature#33]
https://github.com/joyent/node-http-signature/blob/master/lib/verify.js#L34 uses === to compare two base64 encoded hmacs. From a crypto point of view, this is not secure as the comparison leaks timing information.

There are two common ways to address this issue:
1. use a constant time comparison. This is nearly impossible when dealing with a JITed language like javascript, unless you can guarantee that everything is stored in fixed size buffers.
2. hmac each side of the equality operator, blinding any timing information.

You can read more about this here: https://github.com/joyent/node/issues/8560 and on my blog too http://quaxio.com/salted_hmac/.

**Comment by alokmenghrajani** [comment]
Any updates? This is a trivial 5 lines fix...

**Comment by pfmooney** [comment]
@alokmenghrajani PRs welcome.

**Comment by alokmenghrajani** [comment]
https://github.com/joyent/node-http-signature/pull/36

**Comment by dweinstein** [comment]
:+1: would be nice to see this merged in

**Comment by arekinath** [comment]
PR merged, closing this bug
