### ISSUE TITLE
httpsig trusts the algorithm given by the client

### ISSUE THREAD

**Issue by arekinath** [joyent/node-http-signature#40]
Currently in `verify.js` we're trusting the `algorithm` passed in by the client and never verifying what sort of `key` we were given. This is a problem.

Let's imagine we parse the `Authorization` header and look at the `keyId`, then go into our database and get the key with that id. It turns out to be a string of bytes that looks something like `-----BEGIN PUBLIC KEY-----\nMII....`. We take this string of bytes and we give it to `verifySignature`. Note that at no point in this have we ever told node-http-signature that our string of bytes is an RSA key.

Now imagine `verifySignature` runs as normal. In line 31 (https://github.com/joyent/node-http-signature/blob/master/lib/verify.js#L31) it looks at the `algorithm` value which was entirely derived from whatever the client sent in their `Authorization` header. Normally this would say something like `rsa-sha256`, but let's imagine this time it says `hmac-sha1`. Now `verifySignature` will take the opaque string of bytes we gave it (the RSA *public* key) and HMAC the signing string with it and check that against the `signature` value and... oh dear. The public key isn't meant to be secret, is it? Now we're accepting requests from anyone who has the user's *public* key, without them needing the private half at all. Woops.

The only way I can see out of this is to make `verifySignature` take an `algorithm` argument with the `key`. And then `verifySignature` needs to make sure that it matches the parsed `algorithm` value. This should probably just be the first part of the `algorithm` string (ie, `"rsa"`, `"dsa"` or `"hmac"`).

**Comment by pfmooney** [comment]
@arekinath,
Thanks for reporting this. We've decided to split up the API between pubkey signature and HMAC verifications.  The idea was that it should be abundantly clear when a public key versus a shared secret is to be used.  If you have any further feedback, please let us know.
