### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by cbas** [joyent/node-http-signature#49]
Quite a few changes were made since the 0.10.0 release. Time for a version bump and `npm publish`?

(I'm interested because of the removed `asn1@0.1.11` and `ctype@0.5.3` dependencies, which are giving me warnings about their license.)

**Comment by arekinath** [comment]
I'd like to finish off a few more ideas that I'm asking people to review for me at the moment before we cut a release. They're not too revolutionary, so I don't think it'll take too long.

FYI, there is still an indirect dep on `asn1`, but it's the latest version which has the `license` field filled out in its `package.json` (yay). It has always included the MIT license file in the package, though.

**Comment by cbas** [comment]
That sounds great, and thanks for the response! :smile:

**Comment by arekinath** [comment]
Ok, v1.0.0 is now released. https://github.com/joyent/node-http-signature/blob/master/CHANGES.md has the summary of what's new.

**Comment by cbas** [comment]
Btw seems like `http-signature@1.0.0` breaks a test in `request@2.65.0` (latest) so that dependency can't simply be bumped. I'm not familiar enough with `request` nor `http-signature` to know what the breaking changes are. Is this something you're aware of or should I spend some time debugging?

**Comment by rmustacc** [comment]
@cbas we already understand the problem, you don't need to spent time digging into it. You can follow #50 for more information.
