### ISSUE TITLE
1.0.0 doesn't work with request

### ISSUE THREAD

**Issue by mikeal** [joyent/node-http-signature#50]
See, https://github.com/request/request/pull/1837 and the Travis CI builds.

**Comment by arekinath** [comment]
Your test uses a PEM key that lacks a trailing newline after the `-----`. The PEM RFC isn't totally clear on whether this is valid or not, so the behavior seems to vary a little between parsers. The OpenSSL PEM parser is fine with any combination of leading or trailing whitespace though, so I've changed the `sshpk` parser to match this.

The new version of `sshpk` with this fix is `1.4.5`. `http-signature`'s dependency is on `"^1.4.0"`, so re-trying the build should get you a fixed version.
