### ISSUE TITLE
document how to create and verify signatures using openssl

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-http-signature#55]
While debugging #54, I spent a while trying to figure out the right openssl invocations, as well as the correct input formats.  It would be helpful to have some documentation that describes what formats the various files should be in for creating and verifying http-signatures using the openssl tools.

Relatedly, it would be useful if there were a tool that takes some description of an HTTP request (either JSON or the actual HTTP headers or whatever) and a public key file and verifies the signature in the HTTP request using that public key.

**Comment by arekinath** [comment]
I've added examples of using the `openssl` and `sshpk-sign` commands in 0ebeaf26f415707ff79ad3a6c8acc3b05ee494b8, along with other fixes for `http_signing.md`
