### ISSUE TITLE
Bump `assert-plus`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [joyent/node-http-signature#61]
`http-signature` depends on `assert-plus@^0.2.0`.  It also depends on `sshpk`, which depends on `assert-plus@^1.0.0`.  So, currently, `http-signature` requires two versions of `assert-plus`.

**Comment by jaxley** [comment]
BTW, the old version of assert-plus does not work in strict mode so will blow up at runtime.  1.0.0 fixes this.

**Comment by arekinath** [comment]
Fixed as part of joyent/node-http-signature#63
