### ISSUE TITLE
Dependency on sshpk@1.13.1 which contains security vulnerability

### ISSUE THREAD

**Issue by lastrader** [joyent/node-http-signature#70]
https://nodesecurity.io/advisories/606
Can you update to use sshpk >=1.14.1?

**Comment by knoxcard** [comment]
I submitted PR here, but no one is answering...

https://github.com/joyent/node-http-signature/pull/68

**Comment by ar000n** [comment]
@arekinath can you merge this pull request? It's a serious vulnerability

**Comment by sc0ttkclark** [comment]
cc: @trentm @jclulow who both seem to be part of Joyent still

**Comment by jiacfan** [comment]
@trentm  @jclulow Would there be a recent release mitigate this security vulnerable? The PR is merged for days, and a new release is wished.

Thanks,
Jiachen

**Comment by wfortin** [comment]
https://app.snyk.io/vuln/npm:sshpk:20180409 snyk is also complaining about this vulnerability, any way to update sshpk?
Has anyone worked around this while we wait for an official release?

**Comment by jlamillan** [comment]
This looks resolved: https://github.com/joyent/node-http-signature/blob/master/package.json#L35
